Cargo.lock
Cargo.toml
src/attack.rs
src/collisions.rs
src/item.rs
src/main.rs

I've done a replacement of the heron physics crate and the physics code using it for bevy_rapier2d. I tried to stick closely to the original implementations when possible with the equivalent rapier API, with some small changes where necessary.
I believe functionality continues to be the same as it was.
This rewrite was motivated by changes in the bevy_rapier crate which make it more ergonomic and should lead to better support and keeping pace closely with rapier proper since the bevy_rapier is an official integration.

Change physics to bevy_rapier2d

---

src/camera.rs
src/main.rs

Currently, when panning, the camera doesn't move from the camera, however the parallax background layers are moving, the further back the faster.
This PR fixes / improves the camera panning.
The Panning is now handled with a separate component storing the offset from the player. this way you can pan the camera independently from the player position. If you move the player, the camera keeps its offset.
Also, the parallax backgrounds moves correctly with the camera panning.

Camera Panning Fix

---

.github/workflows/ci.yml

This blocks code that is not formatted (note: Actions may need to be activated on this repo).
Note that the other action that the README currently suggests:
```sh
cargo clippy -- -W clippy::correctness -D warnings
```
is not currently possible (without tweaks) because of some Bevy issues/characteristics, e.g. the following (known) problem:
error: call to `std::mem::forget` with a value that does not implement `Drop`. Forgetting such a type is the same as dropping it
--> src/main.rs:102:10
|
102 | #[derive(Bundle)]
|          ^^^^^^
|
note: argument has type `Enemy`
--> src/main.rs:102:10
|
102 | #[derive(Bundle)]
|          ^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#forget_non_drop
= note: this error originates in the derive …

Add GitHub actions CI, with format check

---

Cargo.lock
Cargo.toml
src/animation.rs
src/attack.rs
src/camera.rs
src/main.rs
src/movement.rs
src/state.rs
src/y_sort.rs

Set up bevy-inspector-egui along with its rapier integration crate behind debug feature. Registers some components inspectable. Also moved rapier debug rendering to be behind debug feature. We may want to change this back or we might consider making debug utilities accessible behind a menu or keybind instead of feature flag.
Sets up bevy_mod_debugdump behind shedule_graph feature.
Used by calling `cargo run --features schedule_graph | dot -Tsvg -o output.svg` to render a svg of the system schedule graph.
Closes https://github.com/fishfight/punchy/issues/21

Debug Features

---

assets/beach/beach.level.yaml
src/main.rs
src/metadata.rs

Hot reload fighters and levels!
There is one other way we could have implemented this which has it's own trad-offs.
It's currently implemented by having a system watch for asset updated events. There is one such system for each kind of asset, in this case `Level`s and `Fighter`s. There is a little bit of duplication of the level/fighter spawn logic in the hot reload systems, because we are updating some of the same components, but not all of the components.
The alternative strategy for fighers ( though not for levels because it involves inserting resources ) would be to insert `Handle<Stats>` components onto the fighter entities instead of `Stats` components, for instance.
While this removes the need for a dedicated hot reload system and any duplication in the update logic, it also means …

Hot reload

---

src/attack.rs

Fixed by only running player_attack system in the `InGame` state.

Fix Panic When Pressing Enter on Main Menu

---

src/ui.rs

The background position would end up off if the camera wasn't reset.

Fix Camera Position When Exiting Level

---

src/ui.rs

Forgot to not change the camera Z position when resetting the camera
location after going back to home menu.
Fixes an issue where the camera couldn't see anything but the background
after starting the game, going back to the main menu, and starting the
game again.

Fix Camera Z Position Changing

---

src/main.rs

This is required, in order to avoid 1-frame lag. With the previous design, they would not be able to find items spawned in the same frame.
Closes #37, however, it'd be much better to fully redesign the systems flow in order to take into account 1-frame-lag issues. Moving lag-sensitive systems into PostUpdate makes sense, but it's cleaner design to create one (or more) adhoc stages, in order to structure the flow clearly.

Move move_in_arc and rotate systems to PostUpdate stage

---

Cargo.lock
Cargo.toml
README.md
assets/beach/beach.level.yaml
assets/default.game.yaml
src/attack.rs
src/camera.rs
src/input.rs
src/main.rs
src/metadata.rs
src/movement.rs
src/ui.rs

Here's two players controlled both with gamepads, and keyboard controls work too!

Implement Input Mapping

---

src/ui.rs

Speeds up development cycle, by allowing setting an env var that makes the game go straight to ingame.
There are many approaches to this; this is a very simple one.

Add direct ingame start functionality

---

assets/default.game.yaml
src/camera.rs
src/consts.rs
src/main.rs
src/metadata.rs
src/movement.rs

Closes the first task of #29; the camera has now a proper logic, typical of beat 'em ups.
Boss-related logic is not yet implemented, since there are no bosses yet :laughing:

Proper camera logic, and new player movement limitations

---

src/assets.rs
src/localization.rs

Non-functional change that just removes a closure that I just realized ended up unnecessary.

Remove Unnecessary Closure & Log Message

---

src/config.rs
src/ui.rs

I thought that an engine config parameter made sense as a spot for the new auto-start functionality added by @64kramsystem ( great idea BTW! ).
After I get #34 finished, which is my next task, this will also make it work in the web builds which could be useful.

Use Engine Config For Menu Skip Functionality

---

src/ui.rs

Fixes #67
According to the egui docs it seems like those labels should have existed, but debug dump of the schedule graph seems to indicate otherwise.
It seems to work just fine without the `.before()` and `.after()` flags so I think we'll just remove them and figure out what we need to do if we see issues later.

Fix Missing Label Warnings

---

src/enemy.rs
src/main.rs
src/player.rs

Extract spawning types and logic from main into player.rs and enemy.rs, and extended the respective bundles to make all the components explicit.
Right now, main.rs still has a mix of different things (e.g. player belly flop attack), so other things should be moved out.
There are still some

Refactor fighters spawning

---

Cargo.lock
Cargo.toml
src/game_init.rs

A new update to the input manager allows us to enable multiple gamepads to access menu and camera control.

Allow All Gamepads to Control Camera and Menu

---

Cargo.lock
Cargo.toml

Good to make it consistent with the repo I think. This doesn't change much, but it does make setting the log level for the punchy module much more intuitive.

Rename Crate to `punchy`

---

.github/workflows/build-caches.yml
.github/workflows/ci.yml

Add Clippy correctness checks. In order to make CI run in reasonable time (tens of seconds), a cache workflow has been added, which runs on each master push.
Some notes:
- the master workflow is required, because Github Actions cache is _not_ shared between PRs, but only (within a single PR, or between master and the PRs)
- the other reason to add the master caching workflow is that it can be trivially extended to cache also the build, in case we'll add testing or similar, in the future
This CI will build slowly; after merging, subsequent PRs will run fast.
For example runs/timings, see:
- master workflow run: https://github.com/64kramsystem/punchy-dev/actions/runs/2664626729
- PR workflow run: https://github.com/64kramsystem/punchy-dev/actions/runs/2664677214

CI: Add Clippy correctness checks (and Cargo check data caching)

---

Cargo.lock
Cargo.toml
justfile
src/assets.rs
src/main.rs
src/platform.rs
src/ui.rs
wasm_resources/index.html

Depends on #74.
This implements a `Storage` resource that can be used to access save data, with the details of file IO and browser local storage completely abstracted away to simple string keys and `Serialize + Deserialize` values.
Data is stored in YAML in the user's operating system's data dir on native, and in local storage in the browser.
Currently the abstraction isn't used anywhere, but I did test it with a simple debug gui locally.
I'll be using it to make the input mapping menu next.

Storage abstraction

---

src/player.rs
src/ui/hud.rs

Add the PlayerIndex component, and fixes the HUD list of players not being stable.
A potential refactoring is to draw the player images in the HUD, using a function of their index, rather than iterating them and adding spaces for each iteration.
Closes #81.

Add PlayerIndex component, and fix HUD players ordering

---

Cargo.toml

Even thin LTO (dev default) takes around 30/40% of the compilation time. Since there is not performance pressure right now (in dev), it can be entirely disabled.
See #102.

Disable LTO entirely for dev profile

---

Cargo.toml

As of Jul/2022, opt-level=1 takes a considerable compilation time; with such configuration, profiling a (incremental) build showed that the large part of the time is spent in optimization passes.
Since it's not clear why this happens and how to mitigate it, optimizations are entirely disabled.
It's possible to specify opt-level=1 with lto=false, which is faster, but it's still considerably slower than opt-level=0.
Closes #102.

Remove any optimization for the debug build

---

Cargo.lock
Cargo.toml
assets/default.game.yaml
assets/locales/en-US/main.ftl
src/camera.rs
src/config.rs
src/game_init.rs
src/input.rs
src/main.rs
src/metadata.rs
src/metadata/settings.rs
src/metadata/ui.rs
src/movement.rs
src/platform.rs
src/player.rs
src/ui.rs
src/ui/extensions.rs
src/ui/main_menu.rs
src/ui/pause_menu.rs
src/ui/widgets/bordered_button.rs

It's working! 
Opening as a draft because I need to do a self-review, but it's functional. 🎉

Input Settings Menu

---

.github/workflows/cd.yml

This PR adds a release workflow for creating binary archives when a tag is pushed. It is required for the launcher, see #103
As an example, see the release assets created on my fork: https://github.com/orhun/punchy/releases/tag/v0.0.3

Add GitHub workflow for automated binary releases

---

src/main.rs

This PR avoids getting the game getting stuck (without players), until an actual game over state is added.
Closes #96.

Return to main menu on players death

---

README.md
src/camera.rs
src/game_init.rs

Remove the now orphan Panning component and related code.
Also remove the controls section from the README.

Remove orphan Panning component and related code

---

src/audio.rs

Workaround for what seems to be an unclear behavior of the audio plugin (see comment and related issue).
Closes #121.

Don't play menu music when the autostart flag is set

---

.github/workflows/ci.yml

This PR extends the continuous integration workflow to add a build check for different platforms. It is for making sure that the game builds fine for each push to `master`.

Build for different platforms during CI

---

src/config.rs
src/platform.rs

shouldn't it be "punchy"? haha

Fix "puncy" typos

---

src/main.rs
src/ui/pause_menu.rs
src/utils.rs

Fix World Cleanup and Refactor as System Param

---

src/attack.rs
src/movement.rs

Clamp the player movements/attacks, currently via function. Once the multistage design is implemented, this can be easily split (which will actually simplify the code).
I'm marking this as closes #63 and closes #133, as this effectively fixes the problem. Once the multistage is in place, intention to move is essentially a refactoring.

Implement player movements clamping (currently, via helper function)

---

src/assets.rs

Log a warning and default to english instead of failing the asset load.
Fixes #117

Gracefully Handle Locales That Fail to Parse

---

assets/fighters/bandit/bandit.fighter.yaml
src/attack.rs

Spritesheet changing animation frames caused breakage with hitbox despawning on attacks fixed here.

temp fix for attack frames

---

Cargo.toml

This was breaking WASM release builds. Also I think we may want to leave
it out anyway, because stripping removes panic info that we probably
want, at least this early in development.
Fixes #167

Remove Strip Flag in Release Profile

---

.github/workflows/web-demo.yml
.gitignore
justfile
scripts/build-web.sh
wasm_resources/index.html

- Make web build use it's own target folder to streamline local
development of both native and web builds.
- Make web build URL path agnostic so it can be hosted under any path.
- Make web player build in CI use different paths for each release along
with a latest path that symlinks to the latest release.

Web Build & CI Improvements

---

Cargo.lock
Cargo.toml
macros/Cargo.toml
macros/src/lib.rs
src/assets.rs
src/loading.rs
src/loading/progress.rs
src/metadata.rs
src/metadata/localization.rs
src/metadata/settings.rs
src/metadata/ui.rs

Loading screen still needs to be implemented.
This PR implements a solution for tracking the load progress of game assets.
This works towards #161, but it doesn't implement the UI yet, just the load progress tracking.
It allows us to get the load progress for both `GameMeta` and `LevelMeta` and adds logic to wait until game and level assets are loaded before starting the game/level. This time period should be replaced with a loading screen in a subsequent PR.
Tracking the loading progress for the game is not trivial due to the fact that we have _several_ different kinds of asset and handles referenced throughout the `GameMeta` struct at many different levels of struct nesting.
My initial thought was to add a simple function where I simply manually return all the `HandleId`s in the various …

Implement Load Progress Tracking

---

src/loading.rs

PR #164 broke hot reloading by accidentally triggering asset update
events every time it would check the game load progress.
This moves game load progress checking to a system condition instead
with a read-only borrow to the game asset to prevent the issue.

Fix Bug With Hot Reload and New Loading Progress

---

scripts/build-web.sh

Just a slight tweak that doesn't effect much, but makes sure we don't try to run `wasm-bindgen` if `cargo build` fails.

Make Web Build Script Exit Early on Failure

---

Cargo.lock
Cargo.toml
src/audio.rs
src/config.rs
src/loading.rs
src/main.rs
src/ui/main_menu.rs

EngineConfig is read-only and logically makes sense as a static as it
last the life of the program, so this moves it to a global static that
can be accessed from anywhere in the program instead of just in the Bevy
world.
This is also going to be required for scripting support so that the
asset directory will be readable from asset loaders without borrowing the
Bevy world.

Move EngineConfig to a Static Global

---

assets/beach/beach.level.yaml
src/consts.rs
src/enemy.rs
src/main.rs
src/metadata.rs

Simplest implementation of trip points (replaces enemy FOV).
A trip point is associated to each enemy, which don't set a target unless any player ever trespassed the point. Once a point has been trespassed, the given trip point is set to f32::MIN.
This can be easily changed in the future, for more sophisticated logic (e.g. enemy state change).
Closes #183.

Implement trip points

---

Cargo.lock
Cargo.toml
assets/default.game.yaml
src/animation.rs

This updates the last dep we had out of date, `serde_yaml`, which uses a new syntax for enum tags:
**Before:**
```yaml
up:
SingleAxis:
axis_type:
Gamepad: LeftStickY
positive_low: 0.1
negative_low: -1.0
```
**After:**
```yaml
up: !SingleAxis
axis_type: !Gamepad LeftStickY
positive_low: 0.1
negative_low: -1.0
```
It's a little different than I'm used to. I didn't know YAML had tags, I think it might be a YAML 2.0 feature or something, but I what I _do_ like is that it fixes the inconsistency of using `snake_case` for all of the keys ( leafwing input didn't rename the fields to use snake case like we did ). Since enum tags are now using the `!` syntax and that feels a little bit more consistent and valid to have them use the CamelCase for the tags.
---
Another note is that I had to add a …

Update YAML Version and Cargo Update

---

Cargo.lock
Cargo.toml
src/ui/widgets/bordered_button.rs

Brings our dependency count for builds ( on linux ) from 404 to 376 ( 28 dependencies removed! ). Once https://github.com/dimforge/bevy_rapier/pull/225 is merged we can save an additional dependency on `bevy_pbr`.
Some of the more suspicious dependencies I had noticed that this removes are `bevy_ui` and `bevy_gltf`.

Remove Unneeded Dependencies

---

Cargo.lock
Cargo.toml
assets/default.game.yaml
src/animation.rs
src/platform.rs

Un reverts https://github.com/fishfight/punchy/commit/a60ed4a4864f1c7ff8f5a0633840c94cd9676876 and adds a more graceful fallback to deserialization problems.
The fallback right now is to log an error when we fail to deserialize something, but we just act like the data isn't there afterwards. This means that subsequent attempts to save will overwrite the non-understood value.
This way we get some notification that something unexpected happened, but we don't panic and we can gracefully continue without having to manually modify files on the filesystem or browser storage.

Deserialization Fix

---

src/consts.rs
src/main.rs
src/movement.rs

A mix of tweaks and new logic.
The PR is intended to be the most minimal change that makes a noticeable difference; the main change has been to add an attack distance to Target, which is now randomized (and, in average, smaller), rather than being hardcoded to 100.
On attack, enemies will now always face the target (note: this is not necessarily the player position, but the effect is noticeably better), which looks better, and also improves the attack itself.
The enemy target max offset has also been reduced to 40.
Closes #155.

Improve AI targeting

---

src/fighter_state.rs

This was left-over from a previous design attempt and accidentally left
in.
It's completely unused.
Bors r+

Remove Unused ActionIntents Struct

---

Cargo.toml
assets/locales/en-US/main.ftl
src/animation.rs
src/attack.rs
src/audio.rs
src/camera.rs
src/config.rs
src/fighter.rs
src/loading/progress.rs
src/main.rs
src/movement.rs
src/platform.rs
src/ui.rs
src/ui/debug_tools.rs
src/ui/main_menu.rs

Closes #144.
The `Reflect` derives are used as a more universal way to get support for inspecting them with the Bevy Egui world inspector. 
We will need to derive reflect and register the types for scripting so we might as well not do that and derive `Inspectable`.
This also clears out some of the remaining system scheduling that was done in main.rs and should have been in a plugin.
Now you can show the debug tools menu with F12 and configure the visibility of collision boxes and the world inspector.

Allow Configuring Debug Tools at Runtime

---

assets/beach/beach.level.yaml
assets/fighters/bandit/bandit.fighter.yaml
assets/fighters/big_bass/big_bass.fighter.yaml
assets/fighters/brute/brute.fighter.yaml
assets/fighters/fishy/fishy.fighter.yaml
assets/fighters/sharky/sharky.fighter.yaml
assets/fighters/slinger/slinger.fighter.yaml
src/attack.rs
src/consts.rs
src/enemy_ai.rs
src/fighter_state.rs
src/metadata.rs

This loads basic attack properties from YAML fighter definition files.
AttackFrames, hitbox size and offset relative to fighter are currently loaded.
I've also added a stationary `Punching` attack, used by enemies AI and player. Flop attack still exists but is currently disabled with the intent to re enable after input buffer + attack chain system work.
Fighters now have attack frames which better fit the differing lengths of their attack animations, though the placement and sizing of hitboxes are currently not tuned to match the sprites, though easily modifiable via fighter definitions if need arises.
Direct follow up work to this is additional attack properties loaded from YAML, but this should be left till after other basic attack work is in place.
- Knockback(whether/how much it moves …

Load attack properties from assets

---

src/main.rs
src/ui.rs
src/ui/debug_tools.rs

Fixes #132.
Found out that #132 was caused by the fact that the debug lines plugin that rapier uses to manage debug rendering requires that 4 entities be kept alive to contain the debug lines.
The issue is when we try to reset the world by deleting all entities other than the camera, those entities get deleted, too. And we can't filter those entities out because their distinguishing component is private. Also, there isn't a way to re-create those entities after adding the plugin.
This works around the issue by implementing a custom debug lines renderer for Rapier that uses Egui to draw the lines instead.
It's simple and mostly copied from rapier's plugin.

Fix rapier debug render

---

assets/fighters/bandit/bandit.fighter.yaml
assets/fighters/big_bass/big_bass.fighter.yaml
assets/fighters/brute/brute.fighter.yaml
assets/fighters/fishy/fishy.fighter.yaml
assets/fighters/sharky/sharky.fighter.yaml
assets/fighters/slinger/slinger.fighter.yaml
src/attack.rs
src/camera.rs
src/collision.rs
src/fighter.rs
src/fighter_state.rs
src/metadata.rs

It fixes y-sorting by using the offset in the `YSort `component (not in use before), also implements hurtboxes and updates hitboxes by using a `ColliderMeta`.
Currently, the hurtbox offset is not implemented since it would require spawning the sensor has a child and I'm not sure if that's necessary, at least for now.

Fix YSort and add editable colliders

---

assets/fighters/bandit/bandit.fighter.yaml
assets/fighters/big_bass/big_bass.fighter.yaml
assets/fighters/brute/brute.fighter.yaml
assets/fighters/fishy/fishy.fighter.yaml
assets/fighters/sharky/sharky.fighter.yaml
assets/fighters/slinger/slinger.fighter.yaml
assets/locales/en-US/main.ftl
src/fighter.rs
src/main.rs
src/metadata.rs
src/ui/debug_tools.rs

A PR to draw debug lines for the y-sorting that enables easy debugging for fixing current y-sorting problems.

Debug lines for y-sorting

---

src/attack.rs
src/item.rs

Added a new `DespawnOnCollision` component that takes a number of collisions before it is respawned on collision. Added this component to the projectile bundle with the value of 0.
I do not really like the naming on this one, open to ideas :), should fix #210.

Add projectile despawning on collision.

---

src/fighter_state.rs

I though the fact that you use the healing item in the same way as a weapon a little weird, then, i made these mods to make it "normal".
If it was the intention, I'm sorry, but I don't see any motive to refuse this PR considering that it makes very easier to organize the future new item kinds when grabbed. As I said, if it was the intention, just tell me and I will make the health items be treated as the throwable items, but i don't think there's any reason to refuse this new way of organization. 
Obs: first, I tried to make it possible grab a health even with another item in the inventory, because I forgot that grab and throw are in the same keybind. I think it would be great, but first, these two actions should be divided, so, i have a question: If i divide them, would the PR be …

new healing system | making it easier to organize

---

assets/fighters/big_bass/big_bass.fighter.yaml
assets/levels/1_beach/beach.level.yaml
src/enemy_ai.rs
src/fighter_state.rs

Continued work for #108 
Includes bugfix for the boss' disabled AI as well as some tweaks to the boss attack.

Re-enebled boss ai, unique groundslam attack

---

src/camera.rs
src/consts.rs
src/fighter.rs

Basically, the Y-Sort should take a value with the default Z and maybe some offset if necessary.
Currently, the default Z is defined as a constant with a value of 300.

Change Y-Sort value to represent the base Z value

---

.editorconfig
.github/workflows/web-demo.yml
Cargo.lock
Cargo.toml
assets/default.game.yaml
assets/items/health/health.item.yaml
assets/items/health/health.ts
assets/scripts/demo_script.ts
assets/scripts/log_test.ts
lib.bevy.d.ts
lib.bevy.types.ts
lib.punchy.d.ts
src/assets.rs
src/damage.rs
src/fighter_state.rs
src/item.rs
src/loading.rs
src/main.rs
src/metadata.rs
src/scripting.rs
src/scripting/ops.rs
tsconfig.json

Scripting MVP

---

assets/fighters/bandit/bandit.fighter.yaml
assets/fighters/big_bass/big_bass.fighter.yaml
assets/fighters/brute/brute.fighter.yaml
assets/fighters/dev/dev.fighter.yaml
assets/fighters/fishy/fishy.fighter.yaml
assets/fighters/sharky/sharky.fighter.yaml
assets/fighters/slinger/slinger.fighter.yaml
assets/levels/1_beach/beach.level.yaml
src/attack.rs
src/enemy_ai.rs
src/fighter.rs
src/fighter_state.rs
src/loading.rs
src/main.rs
src/metadata.rs
src/player.rs

~This broke AI as of now, I must have missed some implications of the change, will take another look shortly.
Probably the using the last `AvailableAttack` can have already changed when we are checking its properties before attacks finish.~
Edit: Fixed, should be good to go.

Beginning support for multiple attacks per fighter.

---

assets/fighters/dev/dev.fighter.yaml
src/fighter_state.rs
src/metadata.rs

Only works for a specific sequence of attacks for Dev fighter currently.
Hitting attack during an active "chain" attack will cancel the recovery frames (and a few startup frames on the followup) and move to the next attack.
closes #179 but requires followup work.
Followup should generalize the recovery canceling and attack chain sequence to work for any valid predefined sequence of available attacks on a fighter.

Basic attack chaining

---

Cargo.lock
Cargo.toml
src/animation.rs
src/assets.rs
src/attack.rs
src/audio.rs
src/collision.rs
src/fighter.rs
src/fighter_state.rs
src/item.rs
src/loading.rs
src/localization.rs
src/main.rs
src/metadata.rs
src/movement.rs
src/platform.rs
src/scripting.rs
src/scripting/ops.rs
src/ui.rs
src/ui/debug_tools.rs
src/ui/main_menu.rs

This is from issue https://github.com/fishfolk/punchy/issues/287
Some wrapper types were needed to make bevy 0.9 resources happy.
Changed:
- EguiFontDefinitions that wraps egui::FontDefinitions
- LevelHandle - wraps Handle<LevelMeta>
- GameHandle - wraps Handle<GameMeta>
- Bevy rapier upgraded to using `Group` instead of base u32
- EguiRenderInputContainer - new wrapper type from bevy_egui for HashMap of keys

upgrade to bevy 0.9

---

src/scripting/ops.rs

Updates to use the new namespace for the `wrapValueRef` function in `bevy_mod_js_scripting`.
Fixes: #295

fix: fix scripting error when trying to use health item.

---

src/fighter_state.rs
src/item.rs
src/loading.rs

Boss bomb throw always has another static bomb sprite behind the animated explosion

---

src/assets.rs
src/fighter_state.rs
src/ui/main_menu.rs

This means we can now have attacks which apply damage but do not interrupt other actions/state. Currently in use for the slingers rock throw attack.

Changed hitstun to not transition state if duration is 0
