- Cargo.toml
- src/main.rs
- src/movement.rs
Added a DespawnMarker component and system which despawns all marked entities in the CoreStage::Last stage.
closes #5
> fixed system ordering bug

- Cargo.toml
Feel free to tweak anything you don't like. :)
> Add Optimization Flags to Cargo.toml

- src/animation.rs
- src/assets.rs
- src/main.rs
- src/metadata.rs
- src/ui.rs
Fixes Rust and clippy warnings.
> Clippy fixes

- Cargo.lock
- Cargo.toml
- justfile
- src/main.rs
- src/platform.rs
- wasm_resources/index.html
Runs in a browser! Play it here: https://zicklag.github.io/punchy/demo/
---
I added a `justfile` to help automate the build steps during development using [`just`](https://github.com/casey/just) but we can use plain shell scripts or something else if you want.
> Establish Web Build

- .github/workflows/web-demo.yml
- justfile
Depends on #23.
Play it here: https://zicklag.github.io/punchy/demo/
Fixes #23
This will allow people to follow our progress super easily. We'll have an always up-to-date web demo.
> Ci web demo

- assets/fighters/bandit/bandit.fighter.yaml
- assets/fighters/fishy/fishy.fighter.yaml
- assets/fighters/sharky/sharky.fighter.yaml
- assets/fighters/slinger/slinger.fighter.yaml
- src/animation.rs
- src/metadata.rs
This PR implements a `repeat` value for animations, that defines whether or not an animation should be played in a loop or not.
fixes #35
> Animation Loop

- assets/default.game.yaml
- src/metadata.rs
- src/ui.rs
> Pause menu

- README.md
- src/main.rs
This is purely personal preference, so close if you don't agree, but I feel like the escape button is usually the pause button in computer games.
> Change Pause Button to Escape

- README.md
- src/main.rs
Let me know if you want this in it's own module. I almost put it in a new module, but I wasn't sure what a good module to put it in was, so I figured I'd just ask what you thought first.
It almost could go in `platform`. :thinking:
> Allow Toggling Fullscreen With F11

- src/main.rs
Very tricky one. It's currently unclear why the first frame may run for less Bevy frames than intended; possibly, this is Yet Another One-frame-lag Issue™.
Addresses #48 (unsure if it should close it).
> Workaround for player getting stuck at the bottom

- src/game_init.rs
- src/main.rs
Depends on #56 ( just to avoid having to resolve conflicts ).
Made an attempt to improve the understandability of the game loading by
not using a somewhat cryptic system chain and just using normal systems
and a custom system param.
Hopefully the system param isn't more confusing than the system chain I used earlier?
Let me know if this isn't actually helping.
> Move Game Loading To It's Own Module

- Cargo.lock
- Cargo.toml
- assets/default.game.yaml
- assets/locales/en-US/en-US.ftl.yml
- assets/locales/en-US/main.ftl
- assets/locales/fr-FR/fr-FR.ftl.yml
- assets/locales/fr-FR/main.ftl
- src/assets.rs
- src/game_init.rs
- src/localization.rs
- src/main.rs
- src/metadata.rs
- src/metadata/localization.rs
- src/ui.rs
Depends on #58.
Since it didn't take me long and it's better to do earlier so we don't have to re-do all our strings later, I setup localization!
Currently there's a French and English translation and it's super easy to add new translations. It will auto-detect the language from the users system, even in the browser, which saves us from making a language selection menu for now. :)
> Localization & French Translation

- README.md
- justfile
Shortcut to check code before pull request: `just check`.
> Add Check Recipe to Justfile

- src/camera.rs
- src/movement.rs
> Fix panics on players death

- README.md
It seems that they appreciate if users add the badge ([here](https://app.bors.tech/repositories/46829/settings)), so I think it's nice to do it.
> Add Bors badge to README

- src/audio.rs
Comment is no longer needed. ~ and issue 121 is already closed
> issue 121 is already closed

- src/attack.rs
closes #156 
(something weird happened with git here)
> Add offset to enemy attacks

- src/attack.rs
Player attack damage was hard-coded to 10.
> Read Player Attack Damage From Stats

- src/consts.rs
- src/main.rs
Very simple, based on a fixed X distance.
> Implement Enemy FOV

- .github/bors.toml
- .github/workflows/ci.yml
> CI: Add WASM target to Clippy job

- Cargo.lock
- Cargo.toml
- src/animation.rs
- src/attack.rs
- src/audio.rs
- src/collisions.rs
- src/loading.rs
- src/main.rs
- src/metadata.rs
- src/metadata/settings.rs
- src/movement.rs
- src/platform.rs
- src/ui.rs
- src/ui/main_menu.rs
- src/ui/widgets/bordered_button.rs
It works on Bevy 0.8!
Currently we're depending on the Bevy default features, but that pulls a lot more than we need. I'm going to follow up with a PR to try and cut that down. We have some dependencies depending on Bevy UI, PBR, and Audio, I think and I need to figure out which ones.
> Update to Bevy 0.8 🎉

- .github/ISSUE_TEMPLATE/config.yml
- Cargo.toml
- LICENSE.md
- README.md
- assets/locales/en-US/main.ftl
- src/main.rs
- src/platform.rs
> Update Org Name & Links in README

- Cargo.lock
- Cargo.toml
This gets us hot reload for translation files now, too!
Bors r+
> Update Bevy Fluent to Released Version

- src/localization.rs
- src/metadata/localization.rs
- src/ui/main_menu.rs
- src/ui/pause_menu.rs
It was previously with the metadata. I couldn't find it when I went
looking for it so I think that was a bad spot.
> Move LocalizationExt Trait to `localization.rs`

- assets/locales/en-US/main.ftl
- src/ui/main_menu.rs
Just a very simple PR to say that I have free time to dedicate myself to the project again...
I've tried calling it "throw/grab", but I don't know how to make the .ftl file ignore a "/", so if you know, feel free to fix it.
> making clear to the player

- assets/fighters/bandit/bandit.fighter.yaml
- assets/fighters/big_bass/big_bass.fighter.yaml
- assets/fighters/brute/brute.fighter.yaml
- assets/fighters/fishy/fishy.fighter.yaml
- assets/fighters/sharky/sharky.fighter.yaml
- assets/fighters/slinger/slinger.fighter.yaml
- src/fighter.rs
- src/fighter_state.rs
- src/metadata.rs
Simple refactor, this is necessary for characters with multiple unique attacks.
> Move attack damage to attack definition in YAML

- Cargo.lock
- Cargo.toml
> Update Bevy Parallax to Latest Released Version

- .gitignore
- src/fighter.rs
- src/fighter_state.rs
- src/item.rs
- src/loading.rs
- src/player.rs
- src/ui/hud.rs
Just an initial version for #127, still need to define how items are defined, if by entities or structs with "wrapper" components.
The items are correctly picked up and removed on attack/throw, though this currently leads to a bug since the key to pick up and throw an item is the same. The item gets picked up and thrown before you can lift the key, this kinda makes it hard to see the HUD.
> Inventory system

- src/consts.rs
- src/fighter_state.rs
> gamefeel fixes, updated flopping, knockback priority, timer, velocity.

- assets/default.game.yaml
Disabling the demo script which logged to console for release
> disabled demo script

- src/attack.rs
- src/fighter_state.rs
- src/item.rs
- src/metadata.rs
Changed some logic in hitbox activation system which should ensure it is correct for multiple attacks.
Added collider data directly to attacks on spawn, deduping attack code.
> Attack hitbox insertion and activation refactor

- src/audio.rs
> fixed audio system bug

- assets/fighters/dev/dev.fighter.yaml
- src/fighter_state.rs
Updated assets for Dev and chain system to work with sound effects on each attack.
> sound working for chain attacks

- src/attack.rs
Related to [#267](https://github.com/fishfolk/punchy/issues/267) 
Implements the damage_flash system to make an entity flash white upon receiving damage.
This implementation serves as an alternative to the current system where artists have animated the white flash physically into the frames.
This system is currently used for both player and enemy entities.
> Added code implementation for Hit Flash
